# ======================================================================================
#  __    ____  __  __  ____  ___
# (  )  (_  _)(  \/  )( ___)/ __)
#  )(__  _)(_  )    (  )__) \__ \
# (____)(____)(_/\/\_)(____)(___/
#
#  This file is part of the Limes open source library and is licensed under the terms of the GNU Public License.
#
#  Commercial licenses are available; contact the maintainers at ben.the.vining@gmail.com to inquire for details.
#
# ======================================================================================

# config file for relint, a regular-expression based linter
# see https://github.com/codingjoe/relint
# By default, this tool raises warnings for TODO, NOLINT,
# and cppcheck-suppress tokens found in C++ source files.
# The token NOCOMMIT in any file (except this one) raises
# an error.

- name: TODO
  pattern: 'TODO'
  filePattern: .*\.(h|cpp)
  hint: Found TODO!
  error: false
- name: NOLINT
  pattern: 'NOLINT'
  filePattern: .*\.(h|cpp)
  hint: Found NOLINT!
  error: false
- name: cppcheck-suppress
  pattern: 'cppcheck-suppress'
  filePattern: .*\.(h|cpp)
  hint: Found cppcheck-suppress!
  error: false
- name: if-0
  pattern: '#if 0'
  filePattern: .*\.(h|cpp)
  hint: Found \#if 0!
  error: false
- name: NOCOMMIT
  pattern: 'NOCOMMIT'
  filePattern: .*
  hint: NOCOMMIT token found!
  error: true
